name: Run Pytest

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v7
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: poetry run python -m pytest
